title: Using jekyll-gensocial on your websites
description: >- # this means to ignore newlines until "baseurl:"
  Shows how the jekyll-gensocial plugin works.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jekyll-gensocial.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gensocial

jekyll-gensocial:
  background:
    path: "_assets/img/gensocial_bg.jpg"
  text:
    fill: "#2d3748"
    font_path: "_assets/fonts/Lato-Regular.ttf"
    pointsize: 150
